-- 2026-03-09
-- Dedicate a Tree campaign schema + policies.

create table if not exists public.tree_campaign (
  id bigint generated by default as identity primary key,
  total_quantity integer not null default 18 check (total_quantity >= 0),
  quantity_remaining integer not null default 18 check (quantity_remaining >= 0),
  active boolean not null default true,
  price_per_tree numeric(10,2) not null default 350,
  image_url text null,
  created_at timestamptz not null default now()
);

create table if not exists public.tree_dedications (
  id bigint generated by default as identity primary key,
  transaction_id bigint not null references public."transaction"(id) on delete cascade,
  full_name text not null,
  email text not null,
  dedication_text text not null check (char_length(dedication_text) <= 200),
  dedication_image text null,
  payment_confirmation text not null default 'paid',
  created_at timestamptz not null default now()
);

alter table public."transaction"
  add column if not exists flow_type text null,
  add column if not exists checkout_context jsonb null;

-- Keep active in sync when quantity reaches zero.
create or replace function public.sync_tree_campaign_active()
returns trigger
language plpgsql
as $$
begin
  new.active := (new.quantity_remaining > 0);
  return new;
end;
$$;

drop trigger if exists tree_campaign_sync_active on public.tree_campaign;
create trigger tree_campaign_sync_active
before insert or update on public.tree_campaign
for each row
execute function public.sync_tree_campaign_active();

-- Race-safe stock claim used during payment finalize.
create or replace function public.claim_tree_campaign_unit()
returns table(campaign_id bigint, quantity_remaining integer, price_per_tree numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_campaign_id bigint;
begin
  select id
  into v_campaign_id
  from public.tree_campaign
  where active = true
  order by id asc
  limit 1;

  if v_campaign_id is null then
    return;
  end if;

  return query
  update public.tree_campaign
     set quantity_remaining = quantity_remaining - 1
   where id = v_campaign_id
     and quantity_remaining > 0
  returning id, quantity_remaining, price_per_tree;
end;
$$;

alter table public.tree_campaign enable row level security;
alter table public.tree_dedications enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'tree_campaign' and policyname = 'tree_campaign read anon and auth'
  ) then
    create policy "tree_campaign read anon and auth"
      on public.tree_campaign
      for select
      to anon, authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'tree_campaign' and policyname = 'admins full access tree_campaign'
  ) then
    create policy "admins full access tree_campaign"
      on public.tree_campaign
      for all
      to authenticated
      using (is_admin())
      with check (is_admin());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'tree_dedications' and policyname = 'admins full access tree_dedications'
  ) then
    create policy "admins full access tree_dedications"
      on public.tree_dedications
      for all
      to authenticated
      using (is_admin())
      with check (is_admin());
  end if;
end $$;

insert into public.tree_campaign (total_quantity, quantity_remaining, active, price_per_tree, image_url)
select 18, 18, true, 350, null
where not exists (select 1 from public.tree_campaign);
